DROP TABLE IF EXISTS Kayttaja CASCADE; 
DROP TABLE IF EXISTS Tehtava CASCADE; 
DROP TABLE IF EXISTS Luokka CASCADE; 
DROP TABLE IF EXISTS LuokkaApuTaulukko CASCADE; 
DROP TABLE IF EXISTS AlaluokkaApuTaulukko CASCADE; 